### ISSUE TITLE
.rtorrent.rc being overwritten every time

### ISSUE THREAD

**Issue by petsasj** [mondediefr/docker-rutorrent#75]
Whenever a new image is pushed on dockerhub rutorrent:filebot, and watchtower (or manually) the container is being (re)created, my .rtorrent.rc is being overwritten. 

Also, .rtorrent.rc.old is not what my .rtorrent.rc file used to be somehow.
I have created a copy of my .rtorrent.rc file elsewhere and copy it over everytime I detect a new image is being pushed.

My edited .rtorrent.rc file consists of the same file as the default being created, with just a few more options. It is working and functional.

Finally, on the default configuration (.rtorrent.rc), on the filebot tag, rutorrent displays an error message about the throttle plugin when accessing the page

**Comment by Rathorian** [comment]
Regarding the .rtorrent.rc file, I thought about a new version to proceed. On the last updates, I had to create an .old because otherwise the new parameters that I added were not taken into account.

Regarding the Throttle plugin, I added a fix, just delete the `/config/rutorrent/conf` folder or add in the `/config/rutorrent/conf/config.php` : `$throttleMaxSpeed = 327625* 1024;`

You can see it here: https://github.com/Novik/ruTorrent/commit/06222a00375bdd0f1f1b5b58bda29e7025316428
