### ISSUE TITLE
Plz update rutorrent v4.2.5-hotfix

### ISSUE THREAD

**Issue by lottelucky** [mondediefr/docker-rutorrent#92]
4.2.5 Change Description
Resolved search feature regression with v4.2.3, where a JavaScript error is triggered when searching for torrents.
Resolved view panel bug with v4.2 where the label size feature does not respect the settings in the format menu.

**Comment by Rathorian** [comment]
> 4.2.5 Change Description Resolved search feature regression with v4.2.3, where a JavaScript error is triggered when searching for torrents. Resolved view panel bug with v4.2 where the label size feature does not respect the settings in the format menu.

Hi,

I won't be able to update due to lack of time as soon as a new version is released on the official directory.

However, you can create your personalized image with the new version by doing the following while waiting for me to update or by making a PR:

WITHOUT Filebot:
`docker build --tag custom/rutorrent --build-arg RUTORRENT_VER=4.2.5 https://github.com/mondediefr/docker-rutorrent.git`

WITH Filebot:
`docker build --tag custom/rutorrent:filebot --build-arg FILEBOT=true RUTORRENT_VER=4.2.5 https://github.com/mondediefr/docker-rutorrent.git`

**Comment by lottelucky** [comment]
thanks!
